name: web-performance-auto-generator

# https://crontab.guru/
# ko locale 1 to UTC 16
on:
  schedule:
    - cron: '0 17 * * *'

jobs:
  web-performance-auto-generator:
    name: generate web performance markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: generate report
        run: yarn report-11st

      - name: Update changes in GitHub repository
        run: |
          git config --global user.name 'hochan222'
          git config --global user.email 'hochan049@gmail.com'
          git add -A
          git commit -m '[automated update] generate web performance markdown 11st'
          git push
